algoritmo "Exercício de looping 1; comando Enquanto"
// Função : Repetir o valor de um número a partir do comando "Enquanto"
// Autor :  Matheus Damasceno e Matheus Gama
// Data : 30/03/2023
// Seção de Declarações 
var
  i:inteiro
  ntabu, rtabu:real
inicio
      i:=0
      escreva("Qual número você deseja?: ")
      leia(ntabu)
      enquanto (i <= 10) faca
         rtabu:=ntabu * i
         i:= i+1
         escreva(rtabu)
      fimenquanto
fimalgoritmo
