algoritmo "Atividade de looping 3; comando Para"
// Função : Repetir um número com o uso do comando "Para"
// Autor : Matheus Damasceno e Matheus Gama
// Data : 30/03/2023
// Seção de Declarações
var
i:inteiro
rtabu, ntabu:real
inicio
      escreva("Qual o número você deseja?: ")
      leia(ntabu)
      para i de 0 ate 10 faca
           rtabu:=ntabu * i
           escreva(rtabu)
      fimpara
fimalgoritmo
